// Lightweight isolated controller tests. Browser visual checks are separate.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'web/app.js'),'utf8');
function setup(options={}){
  const elements=new Map(),urls=[],revoked=[],store=new Map();
  if(options.theme)store.set('capturegate-theme',options.theme);
  const element=id=>{if(!elements.has(id))elements.set(id,{hidden:false,textContent:'',dataset:{},style:{},checked:false,files:[],value:'',firstChild:{textContent:''},attributes:{},children:[],classList:{add(){},remove(){}},setAttribute(k,v){this.attributes[k]=v;},removeAttribute(k){delete this.attributes[k];if(k==='src')delete this.src;},replaceChildren(...nodes){this.children=nodes;},append(...nodes){this.children.push(...nodes);},contains(){return false;},click(){}});return elements.get(id);};
  const fixtures=['clean','blur','clipped','glare','blank','missing'].map(f=>({dataset:{fixture:f},disabled:false}));
  const document={documentElement:{dataset:{}},getElementById:element,querySelectorAll:()=>fixtures,querySelector:()=>element('theme-meta'),createElement:()=>element('generated-'+elements.size)};
  const payloads=[];
  const response={decision:'review_ready',reasons:[],detection:'automatic_page_edges',source:'user_supplied',sharpness:100,bright_fraction:0,preview:'data:image/jpeg;base64,YQ==',document_preview:'data:image/jpeg;base64,YQ==',processing_ms:10,policy:'test-only',...options.response};
  const context=vm.createContext({document,window:{addEventListener(){}},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>{if(options.blockStorage)throw Error('blocked');store.set(k,v);}},URL:{createObjectURL:()=>{const url='blob:test-'+urls.length;urls.push(url);return url;},revokeObjectURL:u=>revoked.push(u)},AbortController,Blob,Uint8Array,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),setTimeout,clearTimeout,fetch:async(url,opts)=>{payloads.push(JSON.parse(opts.body));if(options.fetchImpl)return options.fetchImpl(url,opts);if(options.fetchError)throw Error('Network failed');return {ok:true,json:async()=>({...response})};}});
  Object.assign(context,{TextEncoder,DataView,crypto:require('node:crypto').webcrypto});
  vm.runInContext(source,context);
  return {element,document,context,urls,revoked,store,payloads,response,run:code=>vm.runInContext(code,context)};
}
function file(overrides={}){return {name:'sample.jpg',type:'image/jpeg',size:3,arrayBuffer:async()=>Uint8Array.from([1,2,3]).buffer,...overrides};}
function recoverySetup(){return setup({response:{decision:'retake',reasons:['document_boundary_uncertain'],detection:'uncertain',document_preview:null,recovery:{available:true,crop_applied:true,geometry:{may_be_partial:true},original_image:'data:image/jpeg;base64,YQ==',warnings:['May be incomplete.'],variants:['natural','contrast','bw'].map(id=>({id,label:id,image:'data:image/jpeg;base64,YQ==',size:[100,200]})),uncropped_variants:['natural','contrast','bw'].map(id=>({id,label:id,image:'data:image/jpeg;base64,Yg==',size:[300,400]}))}}});}
function acceptRecovery(s){s.element('recovery-confirm').checked=true;s.element('recovery-confirm').onchange();s.element('recovery-accept').onclick();}
test('excluded geometry is explicit and invalid coordinates cannot draw an overlay',()=>{const s=setup();assert.equal(s.run('excludedPath(null)'), '');assert.equal(s.run('excludedPath([[0,0],[2,0],[1,1],[0,1]])'),'');assert.match(s.run('excludedPath([[.1,.1],[.9,.1],[.9,.9],[.1,.9]])'),/M10 10L90 10L90 90L10 90Z/);});
test('matched ZIP requires approval and changes revoke it',async()=>{const s=recoverySetup();await check(s);assert.equal(s.element('download-bundle').disabled,true);await s.element('download-bundle').onclick();assert.equal(s.urls.length,0);acceptRecovery(s);assert.equal(s.element('download-bundle').disabled,false);await s.element('download-bundle').onclick();assert.equal(s.urls.length,1);s.element('recovery-rotate').onclick();assert.equal(s.element('download-bundle').disabled,true);});
test('bundle hash identifies exact bytes and summary retains warnings',async()=>{const s=recoverySetup();await check(s);acceptRecovery(s);const files=await s.run('handoffFiles(Uint8Array.from([97]),report)');assert.deepEqual(Array.from(files,f=>f[0]),['reviewed.jpg','review.json','READ-ME.txt']);const record=JSON.parse(Buffer.from(files[1][1]).toString());assert.equal(record.handoff.output_sha256,require('node:crypto').createHash('sha256').update('a').digest('hex'));assert.equal(record.handoff.identity_verified,false);assert.equal(record.decision,'retake');assert.match(Buffer.from(files[2][1]).toString(),/document_boundary_uncertain/);assert.equal(JSON.stringify(record).includes('data:image'),false);});
test('clearing during hashing prevents stale bundle download',async()=>{const s=recoverySetup();await check(s);acceptRecovery(s);let finish;s.context.crypto={subtle:{digest:()=>new Promise(resolve=>finish=resolve)}};const building=s.element('download-bundle').onclick();await new Promise(resolve=>setImmediate(resolve));s.element('clear').onclick();finish(new Uint8Array(32).buffer);await building;assert.equal(s.urls.length,0);assert.equal(s.element('download-bundle').disabled,true);});
test('changing style during hashing prevents stale bundle download',async()=>{const s=recoverySetup();await check(s);acceptRecovery(s);let finish;s.context.crypto={subtle:{digest:()=>new Promise(resolve=>finish=resolve)}};const building=s.element('download-bundle').onclick();await new Promise(resolve=>setImmediate(resolve));s.element('recovery-bw').onclick();finish(new Uint8Array(32).buffer);await building;assert.equal(s.urls.length,0);});
test('stored ZIP has readable local entries, CRC and central directory',async()=>{const s=setup();const bytes=Buffer.from(await (s.run("zipStored([['reviewed.jpg',Uint8Array.from([97])],['READ-ME.txt',new TextEncoder().encode('Review')]])")).arrayBuffer());assert.equal(bytes.readUInt32LE(0),0x04034b50);assert.equal(bytes.readUInt32LE(14),0xe8b7be43);assert.equal(bytes.subarray(30,42).toString(),'reviewed.jpg');const end=bytes.length-22;assert.equal(bytes.readUInt32LE(end),0x06054b50);assert.equal(bytes.readUInt16LE(end+10),2);assert.equal(bytes.readUInt32LE(bytes.readUInt32LE(end+16)),0x02014b50);});
test('auto crop defaults on; undo and restore preserve style and rotation and revoke acceptance',async()=>{const s=recoverySetup();await check(s);assert.equal(s.run('recoveryCrop'),true);s.element('recovery-contrast').onclick();s.element('recovery-rotate').onclick();acceptRecovery(s);assert.equal(s.run('report.user_review.crop_mode'),'automatic_crop');s.element('recovery-undo').onclick();assert.equal(s.run('canExportRecovery()'),false);assert.equal(s.element('recovery-preview').src,'data:image/jpeg;base64,Yg==');assert.equal(s.run('recoveryRotation'),90);assert.equal(s.run('recoveryIndex'),1);assert.equal(s.element('recovery-restore').hidden,false);acceptRecovery(s);assert.equal(s.run('report.user_review.crop_mode'),'full_photo');s.element('recovery-restore').onclick();assert.equal(s.run('canExportRecovery()'),false);assert.equal(s.element('recovery-preview').src,'data:image/jpeg;base64,YQ==');assert.equal(s.element('recovery-undo').hidden,false);});
test('rotation fits the whole image into its stage at normal zoom',async()=>{const s=recoverySetup();await check(s);assert.equal(s.element('recovery-undo').disabled,false);for(let i=0;i<4;i++){s.element('recovery-rotate').onclick();const w=parseFloat(s.element('recovery-preview-stage').style.width),h=parseFloat(s.element('recovery-preview-stage').style.height);assert.ok(w<=300&&h<=296);assert.match(s.element('recovery-preview').style.transform,/translate\(-50%,-50%\)/);}});
test('new photo resets undone crop and no crop offers no undo',async()=>{const s=recoverySetup();await check(s);s.element('recovery-undo').onclick();await check(s);assert.equal(s.run('recoveryCrop'),true);s.response.recovery.crop_applied=false;await check(s);assert.equal(s.element('recovery-undo').hidden,true);assert.equal(s.element('recovery-restore').hidden,true);});
test('legacy aligned export cannot bypass the selected undo or review version',async()=>{const s=recoverySetup();s.response.decision='review_ready';s.response.reasons=[];s.response.document_preview='data:image/jpeg;base64,YQ==';await check(s);assert.equal(s.element('preview-area').hidden,true);assert.equal(s.element('download-crop').hidden,true);s.element('recovery-undo').onclick();const before=s.urls.length;s.element('download-crop').onclick();assert.equal(s.urls.length,before);acceptRecovery(s);s.element('download-recovered').onclick();assert.equal(s.urls.length,before+1);assert.equal(s.run('report.user_review.crop_mode'),'full_photo');});
test('cleanup requires explicit acceptance without flipping automatic failure',async()=>{const s=recoverySetup();await check(s);blocked(s);assert.equal(s.element('recovery-panel').hidden,false);assert.equal(s.element('recovery-accept').disabled,true);s.element('recovery-accept').onclick();assert.equal(s.run('canExportRecovery()'),false);acceptRecovery(s);assert.equal(s.run('canExportRecovery()'),true);assert.equal(s.run('report.decision'),'retake');assert.equal(s.run('report.user_review.whole_page_certified'),false);blocked(s);s.element('download-recovered').onclick();s.element('download-review').onclick();assert.equal(s.urls.length,2);});
test('human-review JSON strips every preview payload',async()=>{const s=recoverySetup();await check(s);acceptRecovery(s);const serialized=s.run('JSON.stringify(report)');assert.equal(serialized.includes('data:image'),false);assert.equal(serialized.includes('original_image'),false);assert.equal(s.run('report.recovery.variants.length'),3);});
test('variant and rotation changes revoke acceptance',async()=>{const s=recoverySetup();await check(s);acceptRecovery(s);s.element('recovery-bw').onclick();assert.equal(s.run('canExportRecovery()'),false);assert.equal(s.element('recovery-confirm').checked,false);acceptRecovery(s);assert.equal(s.run('report.user_review.variant'),'bw');s.element('recovery-rotate').onclick();assert.equal(s.run('canExportRecovery()'),false);assert.equal(s.run('recoveryRotation'),90);});
test('reject, clear and new check cannot export stale cleanup',async()=>{const s=recoverySetup();await check(s);acceptRecovery(s);s.element('recovery-reject').onclick();assert.equal(s.run('canExportRecovery()'),false);acceptRecovery(s);s.run('start()');assert.equal(s.run('canExportRecovery()'),false);s.element('clear').onclick();assert.equal(s.element('recovery-panel').hidden,true);assert.equal(s.element('recovery-preview').src,undefined);});
test('zoom inspects pixels without accepting a recovery',async()=>{const s=recoverySetup();await check(s);s.element('recovery-zoom').value='2';s.element('recovery-zoom').oninput();assert.equal(s.element('recovery-zoom-label').textContent,'2×');assert.equal(s.run('canExportRecovery()'),false);});
test('default theme and disabled initial analysis',()=>{const s=setup();assert.equal(s.document.documentElement.dataset.theme,'dark');s.run('controls()');assert.equal(s.element('analyze').disabled,true);});
test('theme toggle persists preference and changes accessible label',()=>{const s=setup();s.element('theme-toggle').onclick();assert.equal(s.store.get('capturegate-theme'),'light');assert.equal(s.element('theme-toggle').attributes['aria-label'],'Switch to dark theme');assert.equal(setup({theme:'light'}).document.documentElement.dataset.theme,'light');});
test('blocked preference storage does not break the interface',()=>{const s=setup({blockStorage:true});s.element('theme-toggle').onclick();assert.equal(s.document.documentElement.dataset.theme,'light');});
test('supported selection enables analysis and creates thumbnail',()=>{const s=setup();s.context.testFile=file();s.run('chooseFile(testFile)');assert.equal(s.element('analyze').disabled,false);assert.equal(s.element('selected-preview').hidden,false);assert.equal(s.urls.length,1);});
test('replacing selection revokes its previous thumbnail',()=>{const s=setup();s.context.testFile=file();s.run('chooseFile(testFile);chooseFile(testFile)');assert.deepEqual(s.revoked,['blob:test-0']);});
test('unsupported files and oversized photos cannot start analysis',()=>{for(const f of [file({type:'application/pdf',name:'sample.pdf'}),file({size:4000001})]){const s=setup();s.context.testFile=f;s.run('chooseFile(testFile)');assert.equal(s.element('analyze').disabled,true);assert.equal(s.element('status-card').dataset.state,'error');assert.equal(s.urls.length,0);}});
test('boundary-sized PNG and missing-MIME JPEG extension are accepted',()=>{for(const f of [file({size:4000000,type:'image/png'}),file({type:'',name:'sample.JPEG'})]){const s=setup();s.context.testFile=f;s.run('chooseFile(testFile)');assert.equal(s.element('analyze').disabled,false);}});
test('single dropped file uses the same selection path',()=>{const s=setup();let prevented=false;s.element('drop-zone').ondrop({preventDefault(){prevented=true;},dataTransfer:{files:[file()]}});assert.equal(prevented,true);assert.equal(s.element('analyze').disabled,false);});
test('multiple dropped files are rejected',()=>{const s=setup();s.element('drop-zone').ondrop({preventDefault(){},dataTransfer:{files:[file(),file()]}});assert.equal(s.element('analyze').disabled,true);assert.equal(s.element('status').textContent,'One photo at a time');});
test('clear revokes selection and removes app-held previews',()=>{const s=setup();s.context.testFile=file();s.run('chooseFile(testFile)');s.element('clear').onclick();assert.equal(s.element('selected-preview').hidden,true);assert.equal(s.element('analyze').disabled,true);assert.equal(s.element('session-count').textContent,'Session · 0 checks');assert.deepEqual(s.revoked,['blob:test-0']);});
test('selected photo and chosen corners are dispatched, not replaced with a fixture',async()=>{const s=setup();s.context.testFile=file();s.run('chooseFile(testFile)');await s.element('analyze').onclick();assert.deepEqual(s.payloads,[{image:'AQID',crop_corners:[[0,0],[1,0],[1,1],[0,1]]}]);assert.equal(s.element('status-card').dataset.state,'ready');assert.equal(s.element('source-label').textContent,'Your photo');assert.equal(s.element('session-count').textContent,'Session · 1 check');});

test('upload opens corner editor before any server request; automatic path skips corners',async()=>{const s=setup();s.context.testFile=file();s.run('chooseFile(testFile)');assert.equal(s.element('border-editor').hidden,false);assert.equal(s.payloads.length,0);assert.equal(s.element('border-image').src,'blob:test-0');s.element('border-cancel').onclick();await s.element('analyze').onclick();assert.deepEqual(s.payloads,[{image:'AQID'}]);});
test('keyboard nudging uses original dimensions, clamps corners, shift moves ten pixels',async()=>{const s=recoverySetup();s.response.image_size=[1001,501];await check(s);s.element('recovery-adjust').onclick();s.element('border-0').onkeydown({key:'ArrowRight',shiftKey:true,preventDefault(){}});s.element('border-0').onkeydown({key:'ArrowDown',preventDefault(){}});assert.equal(s.run('manualDraft[0][0]'),.01);assert.equal(s.run('manualDraft[0][1]'),.002);s.element('border-1').onkeydown({key:'ArrowRight',preventDefault(){}});assert.equal(s.run('manualDraft[1][0]'),1);});
test('pointer dragging maps displayed image coordinates and ignores unrelated pointers',async()=>{const s=recoverySetup();await check(s);s.element('recovery-adjust').onclick();s.element('border-stage').getBoundingClientRect=()=>({left:10,top:20,width:200,height:400});s.element('border-0').onpointerdown({pointerId:1,clientX:30,clientY:60,preventDefault(){}});assert.equal(s.run('manualDraft[0][0]'),.1);assert.equal(s.run('manualDraft[0][1]'),.1);s.element('border-0').onpointermove({pointerId:2,clientX:150,clientY:200});assert.equal(s.run('manualDraft[0][0]'),.1);s.element('border-0').onpointermove({pointerId:1,clientX:50,clientY:100,preventDefault(){}});assert.equal(s.run('manualDraft[0][0]'),.2);s.element('border-0').onpointercancel({pointerId:1});assert.equal(s.run('dragCorner'),null);});
test('opening editor revokes acceptance, direct acceptance handlers cannot export drafts',async()=>{const s=recoverySetup();await check(s);acceptRecovery(s);s.element('recovery-adjust').onclick();assert.equal(s.run('canExportRecovery()'),false);s.element('recovery-confirm').checked=true;s.element('recovery-accept').onclick();assert.equal(s.run('canExportRecovery()'),false);s.element('border-cancel').onclick();assert.equal(s.run('canExportRecovery()'),false);assert.equal(s.element('border-editor').hidden,true);});
test('crossed borders do not submit; reset selects full frame; cancel keeps prior crop',async()=>{const s=recoverySetup();await check(s);s.element('recovery-adjust').onclick();s.run('manualDraft=[[0,0],[1,1],[1,0],[0,1]]');const before=s.payloads.length;await s.element('border-apply').onclick();assert.equal(s.payloads.length,before);assert.match(s.element('border-status').textContent,/uncrossed/);s.element('border-reset').onclick();assert.equal(s.run('JSON.stringify(manualDraft)'),JSON.stringify([[0,0],[1,0],[1,1],[0,1]]));s.element('border-cancel').onclick();assert.equal(s.run('recoveryCrop'),true);});
test('applying corners preserves style and rotation, records manual crop and keeps retake',async()=>{const s=recoverySetup();s.response.image_size=[1000,800];await check(s);s.element('recovery-bw').onclick();s.element('recovery-rotate').onclick();s.element('recovery-adjust').onclick();s.run('manualDraft=[[.1,.1],[.9,.1],[.9,.9],[.1,.9]]');s.response.recovery={...s.response.recovery,geometry:{human_selected:true,normalized_corners:[[.1,.1],[.9,.1],[.9,.9],[.1,.9]]}};await s.element('border-apply').onclick();assert.equal(s.element('border-editor').hidden,true);assert.equal(s.run('recoveryIndex'),2);assert.equal(s.run('recoveryRotation'),90);assert.equal(s.run('report.decision'),'retake');assert.equal(s.run('canExportRecovery()'),false);acceptRecovery(s);assert.equal(s.run('report.user_review.crop_mode'),'manual_crop');assert.equal(s.payloads[1].sharpen,false);assert.equal(s.payloads[1].fixture,'test');assert.equal(JSON.stringify(s.payloads[1].crop_corners),JSON.stringify(s.response.recovery.geometry.normalized_corners));assert.equal(s.run('JSON.stringify(report).includes("data:image")'),false);});
test('failed border update retains prior proposal, editor and original warnings',async()=>{const s=recoverySetup();await check(s);s.element('recovery-adjust').onclick();const previous=s.run('imageData.recovery');s.context.fetch=async()=>({ok:false,json:async()=>({error:'Invalid corners'})});await s.element('border-apply').onclick();assert.equal(s.run('imageData.recovery'),previous);assert.equal(s.element('border-editor').hidden,false);assert.equal(s.run('busy'),false);assert.equal(s.run('report.decision'),'retake');assert.match(s.element('border-status').textContent,/Invalid corners/);});
test('sharpening reprocesses same source, retains undone full photo and needs new acceptance',async()=>{const s=recoverySetup();await check(s);s.element('recovery-undo').onclick();acceptRecovery(s);s.response.recovery={...s.response.recovery,sharpened:true};s.element('recovery-sharpen').checked=true;await s.element('recovery-sharpen').onchange();assert.equal(s.payloads[1].sharpen,true);assert.equal(s.run('recoveryCrop'),false);assert.equal(s.run('canExportRecovery()'),false);assert.match(s.element('recovery-variant-label').textContent,/gently sharpened/);acceptRecovery(s);assert.equal(s.run('report.user_review.sharpened'),true);});
test('clearing during crop processing discards late crop response and memory references',async()=>{const s=recoverySetup();await check(s);s.element('recovery-adjust').onclick();let resolve;s.context.fetch=()=>new Promise(r=>resolve=r);const active=s.element('border-apply').onclick();s.element('clear').onclick();resolve({ok:true,json:async()=>({...s.response})});await active;assert.equal(s.run('sourcePayload'),null);assert.equal(s.run('manualDraft'),null);assert.equal(s.element('border-editor').hidden,true);assert.equal(s.run('report'),null);assert.equal(s.element('status').textContent,'Session cleared');});

async function check(s){await s.run('request({fixture:"test"},start())');}
function blocked(s){assert.equal(s.element('actions').hidden,true);assert.equal(s.element('download').disabled,true);assert.equal(s.element('download-crop').disabled,true);const before=s.urls.length;s.element('download').onclick();s.element('download-crop').onclick();assert.equal(s.urls.length,before,'handlers must refuse downloads even if invoked directly');}
test('retake outcomes show prominent rejection and block both exports',async()=>{for(const reason of ['edge_clipped','blur_or_no_detail','bright_region_possible_glare','document_not_found']){const s=setup({response:{decision:'retake',reasons:[reason]}});await check(s);blocked(s);assert.equal(s.element('retake-banner').hidden,false);assert.equal(s.element('preview-area').dataset.state,'retake');assert.match(s.element('status').textContent,/RETAKE REQUIRED/);assert.match(s.element('export-gate').textContent,/Exports locked/);assert.equal(s.element('details').hidden,false);}});
test('uncertain boundary cannot export even if an aligned preview exists',async()=>{const s=setup({response:{decision:'needs_selection',reasons:['document_boundary_uncertain']}});await check(s);blocked(s);assert.equal(s.element('retake-banner').hidden,false);});
test('unsupported boundary preview does not claim an outline or offer alignment',async()=>{const s=setup({response:{decision:'retake',reasons:['document_boundary_uncertain'],detection:'uncertain',document_preview:null}});await check(s);blocked(s);assert.equal(s.element('view-aligned').disabled,true);assert.equal(s.element('preview').alt,'Original photo — no verified page boundary');assert.match(s.element('preview-caption').textContent,/No verified whole-page boundary/);assert.match(s.element('reasons').children[0].textContent,/printed box/);});
test('passed capture enables check record and available aligned JPEG',async()=>{const s=setup();await check(s);assert.equal(s.element('actions').hidden,false);assert.equal(s.element('download').disabled,false);assert.equal(s.element('download-crop').disabled,false);assert.equal(s.element('retake-banner').hidden,true);s.element('download').onclick();s.element('download-crop').onclick();assert.equal(s.urls.length,2);});
test('contradictory ready result with failure reasons is blocked',async()=>{const s=setup({response:{reasons:['edge_clipped']}});await check(s);blocked(s);assert.equal(s.element('status-card').dataset.state,'retake');});
test('ready result without aligned image enables JSON only',async()=>{const s=setup({response:{document_preview:null}});await check(s);assert.equal(s.element('download').disabled,false);assert.equal(s.element('download-crop').hidden,true);const before=s.urls.length;s.element('download-crop').onclick();assert.equal(s.urls.length,before);});
test('new check and clear cannot export the previous successful capture',async()=>{const s=setup();await check(s);s.run('start()');blocked(s);assert.equal(s.element('preview-area').hidden,true);s.element('clear').onclick();blocked(s);assert.equal(s.element('export-gate').hidden,true);});
test('ready-to-retake transition removes success exports',async()=>{const s=setup();await check(s);s.response.decision='retake';s.response.reasons=['blur_or_no_detail'];await check(s);blocked(s);assert.equal(s.element('retake-banner').hidden,false);});
test('failed request after success cannot export stale data',async()=>{const options={};const s=setup(options);await check(s);options.fetchError=true;await check(s);blocked(s);assert.equal(s.element('status-card').dataset.state,'error');});
test('out-of-order response cannot replace the latest successful check',async()=>{const pending=[];const s=setup({fetchImpl:(url,opts)=>new Promise(resolve=>pending.push({opts,resolve}))});const first=check(s);const second=check(s);assert.equal(pending[0].opts.signal.aborted,true);pending[1].resolve({ok:true,json:async()=>({...s.response})});await second;pending[0].resolve({ok:true,json:async()=>({...s.response,decision:'retake',reasons:['edge_clipped']})});await first;assert.equal(s.element('status-card').dataset.state,'ready');assert.equal(s.element('session-count').textContent,'Session · 1 check');assert.equal(s.element('download').disabled,false);});
test('late response after clearing cannot recreate previews or exports',async()=>{const pending=[];const s=setup({fetchImpl:(url,opts)=>new Promise(resolve=>pending.push({opts,resolve}))});const active=check(s);s.element('clear').onclick();assert.equal(pending[0].opts.signal.aborted,true);pending[0].resolve({ok:true,json:async()=>({...s.response})});await active;blocked(s);assert.equal(s.element('session-count').textContent,'Session · 0 checks');assert.equal(s.element('preview-area').hidden,true);assert.equal(s.element('status').textContent,'Session cleared');});
