'use strict';
const $ = id => document.getElementById(id);
let report = null, imageData = null, sequence = 0, busy = false, controller = null, checks = 0, previousRetake = null, selectedFile = null, selectedUrl = null;
let recoveryIndex=0,recoveryRotation=0,recoveryAccepted=false,recoveryCrop=true;
let sourcePayload=null,manualEditing=false,manualDraft=null,manualBeforeCheck=false,dragCorner=null;
const fullBorder=()=>[[0,0],[1,0],[1,1],[0,1]];
function closeBorder(){manualEditing=false;manualDraft=null;dragCorner=null;$('border-editor').hidden=true;$('border-image').removeAttribute('src');}
function cleanReport(data){const record={...data};delete record.preview;delete record.document_preview;if(data.recovery){record.recovery={...data.recovery};for(const key of ['variants','uncropped_variants'])record.recovery[key]=(data.recovery[key]||[]).map(({image,...metadata})=>metadata);delete record.recovery.original_image;}return record;}
const explanations = {edge_clipped:'Move the camera back until every page edge is visible. Leave a small border around the paper.',blur_or_no_detail:'Hold the camera steady and tap to focus on the text. Check that the page contains visible detail.',bright_region_possible_glare:'A bright patch may hide detail. Change the angle or lighting, then inspect the affected text.',document_not_found:'Place one bright page on a darker surface, with all four corners visible.',document_boundary_uncertain:'The whole-page boundary could not be verified. A printed box is not necessarily the page edge. Move back and use a darker surface, with all four paper corners visible.'};
function controls(){for(const b of document.querySelectorAll('[data-fixture]'))b.disabled=busy;$('input-adjust').disabled=busy||!selectedFile;$('analyze').disabled=busy||!selectedFile;$('analyze').firstChild.textContent=busy?'Checking…':manualEditing&&manualBeforeCheck?'Apply borders & check ':'Check photo ';}
function status(state,title,detail){$('status-card').dataset.state=state;$('status').textContent=title;$('status-detail').textContent=detail;$('status-symbol').textContent={idle:'◎',busy:'◌',retake:'↻',ready:'✓',error:'!'}[state];}
function canExport(){return !busy&&!manualEditing&&report?.decision==='review_ready'&&Array.isArray(report.reasons)&&report.reasons.length===0;}
function canExportAligned(){return canExport()&&!!imageData?.document_preview&&!imageData?.recovery?.available;}
function exportControls(){const allowed=canExport();$('actions').hidden=!allowed;$('download').disabled=!allowed;$('download-crop').disabled=!canExportAligned();$('download-crop').hidden=!canExportAligned();}
function reset(){sequence++;if(controller)controller.abort();controller=null;busy=false;sourcePayload=null;closeBorder();report=null;imageData=null;recoveryIndex=0;recoveryRotation=0;recoveryAccepted=false;recoveryCrop=true;for(const id of ['preview-area','quality-grid','details','actions','export-gate','source-label','comparison','recovery-panel','recovery-actions'])$(id).hidden=true;recoveryControls();$('recovery-original').removeAttribute('src');$('recovery-preview').removeAttribute('src');exportControls();$('preview').removeAttribute('src');$('reasons').replaceChildren();$('metrics').textContent='';$('empty').hidden=false;controls();}
function metric(id,value,ok){$(id).textContent=value;$(id).dataset.ok=String(ok);}
function revealResult(){if(window.matchMedia?.('(max-width:760px)')?.matches)$('result-heading').scrollIntoView?.({block:'start',behavior:window.matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});}
function setView(aligned){if(!imageData)return;const uncertain=imageData.detection==='uncertain'||imageData.reasons.includes('document_not_found');$('preview').src=aligned?imageData.document_preview:imageData.preview;$('preview').alt=aligned?'Automatically aligned document crop':uncertain?'Original photo — no verified page boundary':'Photo with automatically detected document boundary';$('view-original').setAttribute('aria-pressed',String(!aligned));$('view-aligned').setAttribute('aria-pressed',String(aligned));$('preview-caption').textContent=aligned?'Geometric alignment only. Compare with the original and confirm no content was lost.':uncertain?'No verified whole-page boundary. This original photo is diagnostic only; retake before handoff.':'Outline shows the detected boundary. Check it against the actual paper.';}
async function request(payload,ticket){sourcePayload={...payload};delete sourcePayload.crop_corners;delete sourcePayload.sharpen;controller=new AbortController();const currentController=controller;const timeout=setTimeout(()=>currentController.abort(),20000);try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:currentController.signal});const data=await response.json();if(ticket!==sequence)return;if(!response.ok)throw Error(data.error||'Analysis failed');imageData=data;report=cleanReport(data);checks++;$('session-count').textContent='Session · '+checks+(checks===1?' check':' checks');
const ready=data.decision==='review_ready'&&Array.isArray(data.reasons)&&data.reasons.length===0;status(ready?'ready':'retake',ready?'Capture checks passed — review the page':'RETAKE REQUIRED — not usable for handoff',ready?'Page candidate found. Confirm every edge and line of text is correct before using it.':'This capture failed the checks. Retake it before downloading or handing it off.');
$('retake-banner').hidden=ready;$('preview-area').dataset.state=ready?'ready':'retake';
$('source-label').hidden=false;$('source-label').textContent=data.source==='synthetic'?'Generated example':'Your photo';
const hasBoundary=data.detection==='automatic_page_edges'||data.detection==='automatic';metric('framing-state',data.reasons.includes('edge_clipped')?'Cut-off edge':hasBoundary?'Candidate found':'Not isolated',hasBoundary&&!data.reasons.includes('edge_clipped'));metric('detail-state',data.sharpness===undefined?'Not checked':data.reasons.includes('blur_or_no_detail')?'Low detail':'Check passed',data.sharpness!==undefined&&!data.reasons.includes('blur_or_no_detail'));metric('light-state',data.bright_fraction===undefined?'Not checked':data.reasons.includes('bright_region_possible_glare')?'Inspect bright patch':'No patch flagged',data.bright_fraction!==undefined&&!data.reasons.includes('bright_region_possible_glare'));
$('quality-grid').hidden=false;$('empty').hidden=true;$('preview-area').hidden=false;$('timing').textContent=Number.isFinite(data.processing_ms)?data.processing_ms.toFixed(0)+' ms · server processing':'Timing unavailable on this server';$('view-aligned').disabled=!data.document_preview;$('download-crop').hidden=!data.document_preview;setView(!!data.document_preview);
for(const reason of data.reasons){const p=document.createElement('p');p.textContent=(data.recovery?.available?'Original capture warning: ':'')+(explanations[reason]||reason);$('reasons').append(p);}
if(ready&&previousRetake&&previousRetake.source===data.source){$('comparison').replaceChildren();const title=document.createElement('strong');title.textContent='A better capture, a clearer handoff';const body=document.createElement('span');body.textContent='Previous check: '+previousRetake.reasons.map(r=>({edge_clipped:'cut-off edge',blur_or_no_detail:'low detail',bright_region_possible_glare:'bright patch',document_not_found:'no page',document_boundary_uncertain:'uncertain boundary'}[r]||r)).join(', ')+'. This capture passes the current checks. This compares session checks; it does not prove both photos show the same document.';$('comparison').append(title,body);$('comparison').hidden=false;}
if(!ready)previousRetake={source:data.source,reasons:[...data.reasons]};
showRecovery();
$('metrics').textContent=JSON.stringify(report,null,2);$('details').hidden=false;$('export-gate').hidden=false;$('export-gate').textContent=ready&&data.reasons.length===0?'Exports available for human review. The JSON is a check record, not extracted document text.':data.recovery?.available?'Automatic-pass exports remain locked. You may separately accept a cleanup above and save it as human-reviewed; the original warnings remain recorded.':'Exports locked. Retake the photo and pass the capture checks before downloading a page or check record. Diagnostic measurements remain available below.';revealResult();
}catch(error){if(ticket===sequence){report=null;imageData=null;recoveryAccepted=false;$('recovery-panel').hidden=true;recoveryControls();exportControls();status('error',error.name==='AbortError'?'The check took too long':'Unable to check this photo',error.name==='AbortError'?'Try once more with a smaller image. Your original photo is unchanged.':error.message);}}finally{clearTimeout(timeout);if(ticket===sequence){busy=false;controller=null;controls();exportControls();recoveryControls();}}}

function recoveryVariant(){const r=imageData?.recovery;return r?.available?(recoveryCrop?r.variants:r.uncropped_variants)?.[recoveryIndex]:null;}
function canExportRecovery(){return !busy&&!manualEditing&&!!report&&!!recoveryVariant()&&recoveryAccepted&&report.user_review?.accepted===true;}
function recoveryControls(){const available=!!recoveryVariant(),locked=busy||manualEditing;$('recovery-confirm').disabled=locked||!available;$('recovery-accept').disabled=locked||!available||!$('recovery-confirm').checked;for(const id of ['recovery-undo','recovery-restore','recovery-adjust','recovery-sharpen','recovery-natural','recovery-contrast','recovery-bw','recovery-rotate','recovery-reject'])$(id).disabled=locked||!available;for(const id of ['border-apply','border-reset','border-cancel','border-0','border-1','border-2','border-3'])$(id).disabled=busy;$('recovery-actions').hidden=!canExportRecovery();$('download-recovered').disabled=!canExportRecovery();$('download-review').disabled=!canExportRecovery();}
function revokeRecovery(){recoveryAccepted=false;$('recovery-confirm').checked=false;if(report)delete report.user_review;$('recovery-review-status').textContent='Review required. Cleanup downloads are locked.';recoveryControls();if(report){$('metrics').textContent=JSON.stringify(report,null,2);if(report.decision!=='review_ready'&&recoveryVariant())status('retake','Cleanup ready — compare before deciding','Automatic checks did not pass. Inspect the proposed versions, accept one for your use, or retake.');}}
function fitRecovery(){const v=recoveryVariant();if(!v)return;const zoom=Math.max(1,Math.min(3,Number($('recovery-zoom').value)||1));$('recovery-zoom-label').textContent=zoom+'×';for(const [kind,size,rotation] of [['original',imageData.recovery.uncropped_variants?.[0]?.size||v.size,0],['preview',v.size,recoveryRotation]]){const [w,h]=size;const rw=rotation%180?h:w,rh=rotation%180?w:h;const frame=$('recovery-'+kind+'-frame');const scale=Math.min(Math.max(40,(frame.clientWidth||324)-24)/rw,Math.max(40,(frame.clientHeight||320)-24)/rh)*zoom;const stage=$('recovery-'+kind+'-stage'),img=$('recovery-'+kind);stage.style.width=(rw*scale)+'px';stage.style.height=(rh*scale)+'px';img.style.width=(w*scale)+'px';img.style.height=(h*scale)+'px';img.style.transform='translate(-50%,-50%) rotate('+rotation+'deg)';}}
function renderRecovery(){const v=recoveryVariant();if(!v)return;$('recovery-preview').src=v.image;const r=imageData.recovery;const cropped=recoveryCrop&&r.crop_applied,manual=r.geometry?.human_selected===true;$('recovery-variant-label').textContent=(cropped?(manual?'Your crop · ':'Auto crop · '):'Full photo · ')+v.label+(r.sharpened?' · gently sharpened':'')+(recoveryRotation?' · rotated '+recoveryRotation+'°':'');$('recovery-undo').textContent=manual?'Undo crop':'Undo auto crop';$('recovery-restore').textContent=manual?'Restore your crop':'Restore auto crop';$('recovery-sharpen').checked=!!r.sharpened;$('recovery-undo').hidden=!cropped;$('recovery-restore').hidden=recoveryCrop||!r.crop_applied;$('recovery-crop-status').textContent=cropped?(manual?'Your borders applied — inspect the result. Undo or adjust if anything needed is cut off.':r.geometry?.may_be_partial?'Auto crop applied to visible edges — some page edges are missing. Undo if needed.':'Auto crop applied to detected page edges. Undo if it cuts off anything needed.'):r.crop_applied?'Crop undone — full photo restored. Color and rotation remain your choice.':'No usable edge crop found — full photo retained. Retake if needed.';for(const [i,id] of ['natural','contrast','bw'].entries())$('recovery-'+id).setAttribute('aria-pressed',String(i===recoveryIndex));fitRecovery();}
function showRecovery(){recoveryCrop=true;if(!recoveryVariant()){ $('recovery-panel').hidden=true;return; }revokeRecovery();$('recovery-panel').hidden=false;$('preview-area').hidden=true;$('recovery-original').src=imageData.recovery.original_image||imageData.preview;$('recovery-note').textContent=imageData.recovery.warnings.join(' ');$('recovery-zoom').value='1';renderRecovery();if(report.decision!=='review_ready'){$('retake-banner').hidden=true;status('retake','Cleanup ready — compare before deciding','Automatic checks did not pass. Inspect the proposed versions, accept one for your use, or retake.');}}
function renderBorder(){if(!manualDraft)return;$('border-outline').setAttribute('points',manualDraft.map(p=>p.map(v=>v*100).join(',')).join(' '));$('border-excluded').setAttribute('d',excludedPath(manualDraft));manualDraft.forEach(([x,y],i)=>{const handle=$('border-'+i);handle.style.left=(x*100)+'%';handle.style.top=(y*100)+'%';handle.setAttribute('aria-description','Position '+(x*100).toFixed(1)+'%, '+(y*100).toFixed(1)+'%.');});}
function openBorder(beforeCheck=false){if(busy||beforeCheck&&!selectedFile||!beforeCheck&&!imageData?.recovery?.available)return;manualBeforeCheck=beforeCheck;manualDraft=fullBorder();if(!beforeCheck&&recoveryCrop){const g=imageData.recovery.geometry||{},size=imageData.image_size;if(g.normalized_corners)manualDraft=g.normalized_corners.map(p=>[...p]);else if(size&&g.source_corners)manualDraft=g.source_corners.map(([x,y])=>[x/(size[0]-1),y/(size[1]-1)]);else if(size&&g.source_box){const [x,y,w,h]=g.source_box;manualDraft=[[x,y],[x+w-1,y],[x+w-1,y+h-1],[x,y+h-1]].map(([x,y])=>[x/(size[0]-1),y/(size[1]-1)]);}}manualDraft=manualDraft.map(p=>p.map(v=>Math.max(0,Math.min(1,v))));manualEditing=true;revokeRecovery();$('border-editor').hidden=false;$('empty').hidden=true;$('border-image').src=beforeCheck?selectedUrl:imageData.recovery.original_image;$('border-apply').textContent=beforeCheck?'Apply borders & check':'Apply borders';$('border-cancel').textContent=beforeCheck?'Use automatic edges':'Cancel adjustment';$('border-status').textContent='Border preview only. Nothing is applied yet.';renderBorder();controls();recoveryControls();exportControls();$('border-heading').scrollIntoView?.({block:'start',behavior:'auto'});}
function moveBorder(i,x,y){if(!manualEditing||busy)return;manualDraft[i]=[Math.max(0,Math.min(1,x)),Math.max(0,Math.min(1,y))];$('border-status').textContent='Border changed. Apply to preview the cropped page.';renderBorder();}
function validBorder(){if(!manualDraft)return false;const size=manualBeforeCheck?[$('border-image').naturalWidth||1000,$('border-image').naturalHeight||1000]:imageData.image_size||[1000,1000];const pts=manualDraft.map(([x,y])=>[x*(size[0]-1),y*(size[1]-1)]);let sign=0,area=0;for(let i=0;i<4;i++){const a=pts[i],b=pts[(i+1)%4],c=pts[(i+2)%4],cross=(b[0]-a[0])*(c[1]-b[1])-(b[1]-a[1])*(c[0]-b[0]);if(!Number.isFinite(cross)||Math.abs(cross)<.001||Math.hypot(b[0]-a[0],b[1]-a[1])<10)return false;if(sign&&Math.sign(cross)!==sign)return false;sign=Math.sign(cross);area+=a[0]*b[1]-b[0]*a[1];}return Math.abs(area)>=200;}
for(let i=0;i<4;i++){const handle=$('border-'+i);const point=e=>{const r=$('border-stage').getBoundingClientRect();if(r.width>0&&r.height>0)moveBorder(i,(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height);};handle.onpointerdown=e=>{if(!manualEditing||busy)return;e.preventDefault();dragCorner={index:i,id:e.pointerId};handle.setPointerCapture?.(e.pointerId);point(e);};handle.onpointermove=e=>{if(dragCorner?.index===i&&dragCorner.id===e.pointerId){e.preventDefault();point(e);}};handle.onpointerup=handle.onpointercancel=e=>{if(dragCorner?.index===i&&dragCorner.id===e.pointerId)dragCorner=null;};handle.onkeydown=e=>{if(!manualEditing||busy||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const size=manualBeforeCheck?[$('border-image').naturalWidth||1000,$('border-image').naturalHeight||1000]:imageData.image_size||[1000,1000];const step=e.shiftKey?10:1,[x,y]=manualDraft[i];moveBorder(i,x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0)/(size[0]-1),y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)/(size[1]-1));};}
async function updateCleanup(corners,sharpen,applyCrop=false){if(busy||!sourcePayload||!imageData)return;const ticket=++sequence,wasCrop=recoveryCrop;busy=true;revokeRecovery();controls();recoveryControls();exportControls();$('border-status').textContent='Applying your borders…';$('recovery-review-status').textContent='Updating preview. Downloads are locked.';controller=new AbortController();const active=controller,timeout=setTimeout(()=>active.abort(),20000);try{const payload={...sourcePayload,sharpen};if(corners)payload.crop_corners=corners;const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:active.signal});const data=await response.json();if(ticket!==sequence)return;if(!response.ok)throw Error(data.error||'Unable to update the preview');if(!data.recovery?.available)throw Error('No usable proposal. Your previous preview is retained.');imageData={...imageData,recovery:data.recovery};report={...report,recovery:cleanReport(data).recovery};delete report.user_review;recoveryCrop=applyCrop?true:wasCrop;closeBorder();$('recovery-note').textContent=data.recovery.warnings.join(' ');renderRecovery();$('metrics').textContent=JSON.stringify(report,null,2);$('recovery-review-status').textContent='Updated preview. Inspect and accept this exact version before saving.';}catch(error){if(ticket===sequence){const message=error.name==='AbortError'?'The update timed out. Previous preview retained.':error.message;$('border-status').textContent=message;$('recovery-review-status').textContent=message;renderRecovery();}}finally{clearTimeout(timeout);if(ticket===sequence){busy=false;controller=null;controls();recoveryControls();exportControls();}}}
$('recovery-adjust').onclick=()=>openBorder(false);
$('input-adjust').onclick=()=>openBorder(true);
$('border-reset').onclick=()=>{if(!manualEditing||busy)return;manualDraft=fullBorder();renderBorder();$('border-status').textContent='Full photo selected. Adjust the corners before applying.';};
$('border-cancel').onclick=()=>{if(busy)return;const before=manualBeforeCheck;closeBorder();controls();recoveryControls();exportControls();if(before)status('idle','Photo selected — automatic edges','Press Check photo to let the detector propose a border.');};
$('border-apply').onclick=async()=>{if(!manualEditing||busy)return;if(!validBorder()){$('border-status').textContent='Corners must form an uncrossed border with each edge at least 10 pixels long.';return;}if(manualBeforeCheck)return $('analyze').onclick();await updateCleanup(manualDraft.map(p=>[...p]),!!imageData.recovery.sharpened,true);};
$('recovery-sharpen').onchange=()=>{if(busy||manualEditing){$('recovery-sharpen').checked=!!imageData?.recovery?.sharpened;return;}return updateCleanup(imageData?.recovery?.geometry?.normalized_corners||null,$('recovery-sharpen').checked);};
for(const [i,id] of ['natural','contrast','bw'].entries())$('recovery-'+id).onclick=()=>{if(!recoveryVariant()||busy||manualEditing)return;recoveryIndex=i;revokeRecovery();renderRecovery();};
$('recovery-undo').onclick=()=>{if(busy||manualEditing||!imageData?.recovery?.crop_applied||!imageData.recovery.uncropped_variants)return;recoveryCrop=false;revokeRecovery();renderRecovery();};
$('recovery-restore').onclick=()=>{if(busy||manualEditing||!imageData?.recovery?.crop_applied)return;recoveryCrop=true;revokeRecovery();renderRecovery();};
$('recovery-rotate').onclick=()=>{if(!recoveryVariant()||busy||manualEditing)return;recoveryRotation=(recoveryRotation+90)%360;revokeRecovery();renderRecovery();};
$('recovery-zoom').oninput=fitRecovery;
window.addEventListener('resize',()=>{if(!$('recovery-panel').hidden)fitRecovery();});
$('recovery-confirm').onchange=()=>{if(recoveryAccepted)revokeRecovery();recoveryControls();};
$('recovery-accept').onclick=()=>{if(busy||manualEditing||!recoveryVariant()||!$('recovery-confirm').checked)return;recoveryAccepted=true;const r=imageData.recovery;report.user_review={accepted:true,variant:recoveryVariant().id,crop_mode:recoveryCrop&&r.crop_applied?(r.geometry?.human_selected?'manual_crop':'automatic_crop'):'full_photo',sharpened:!!r.sharpened,rotation_degrees:recoveryRotation,scope:'user_accepts_visible_content_for_own_use',automatic_decision:report.decision,automatic_reasons:[...report.reasons],whole_page_certified:false};$('recovery-review-status').textContent='You accepted this exact version. This is human acceptance, not an automatic whole-page pass.';status(report.decision==='review_ready'?'ready':'retake','Version accepted by you — original check retained','Reviewed-version downloads are available. Acceptance does not certify the whole page or change the original check.');$('metrics').textContent=JSON.stringify(report,null,2);recoveryControls();};
$('recovery-reject').onclick=()=>{revokeRecovery();$('recovery-review-status').textContent='Retake selected. Capture again with all needed content visible.';status('retake','Retake selected','The proposed cleanup was not acceptable. Your original photo is unchanged.');};
$('download-review').onclick=()=>{if(canExportRecovery())download(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),'capturegate-human-reviewed.json');};
$('download-recovered').onclick=async()=>{if(!canExportRecovery())return;const variant=recoveryVariant(),rotation=recoveryRotation,ticket=sequence;if(rotation===0){const bytes=atob(variant.image.split(',')[1]);download(new Blob([Uint8Array.from(bytes,c=>c.charCodeAt(0))],{type:'image/jpeg'}),'capturegate-human-reviewed.jpg');return;}const img=new Image();img.src=variant.image;try{await img.decode();if(ticket!==sequence||variant!==recoveryVariant()||rotation!==recoveryRotation||!canExportRecovery())return;const canvas=document.createElement('canvas');canvas.width=rotation%180?img.naturalHeight:img.naturalWidth;canvas.height=rotation%180?img.naturalWidth:img.naturalHeight;const context=canvas.getContext('2d');context.translate(canvas.width/2,canvas.height/2);context.rotate(rotation*Math.PI/180);context.drawImage(img,-img.naturalWidth/2,-img.naturalHeight/2);canvas.toBlob(blob=>{if(blob&&ticket===sequence&&variant===recoveryVariant()&&rotation===recoveryRotation&&canExportRecovery())download(blob,'capturegate-human-reviewed.jpg');},'image/jpeg',.90);}catch{$('recovery-review-status').textContent='Unable to export the rotated version. Try the unrotated version or retake.';}};
function start(){reset();busy=true;controls();status('busy','Checking the capture…','Finding page edges, measuring detail and checking bright regions.');return sequence;}
for(const b of document.querySelectorAll('[data-fixture]'))b.onclick=()=>{const ticket=start();request({fixture:b.dataset.fixture},ticket);};
function releaseSelection(){selectedFile=null;if(selectedUrl)URL.revokeObjectURL(selectedUrl);selectedUrl=null;$('selected-preview').removeAttribute('src');$('selected-preview').hidden=true;}
function chooseFile(file){reset();releaseSelection();$('file-name').textContent=file?file.name+' · '+(file.size/1000000).toFixed(2)+' MB':'No photo selected';if(file&&(file.size>4000000||(!['image/png','image/jpeg'].includes(file.type)&&!(!file.type&&/\.(png|jpe?g)$/i.test(file.name))))){status('error','Choose a supported photo','Use one PNG or JPEG no larger than 4 MB. Your original file is unchanged.');controls();return;}selectedFile=file||null;if(selectedFile){selectedUrl=URL.createObjectURL(selectedFile);$('selected-preview').src=selectedUrl;$('selected-preview').hidden=false;openBorder(true);}controls();status('idle',file?'Photo selected — set your borders':'Ready when you are',file?'Adjust the four corners, then apply and check. Or choose Use automatic edges.':'Add a photo or explore a scenario to start your check.');}
$('file').onchange=()=>chooseFile($('file').files[0]);
const zone=$('drop-zone');
zone.ondragover=e=>{e.preventDefault();zone.classList.add('dragging');e.dataTransfer.dropEffect='copy';};
zone.ondragleave=e=>{if(!zone.contains(e.relatedTarget))zone.classList.remove('dragging');};
zone.ondrop=e=>{e.preventDefault();zone.classList.remove('dragging');$('file').value='';if(e.dataTransfer.files.length!==1){chooseFile(null);status('error','One photo at a time','Drop one PNG or JPEG to start a capture check.');return;}chooseFile(e.dataTransfer.files[0]);};
$('analyze').onclick=async()=>{const file=selectedFile;if(!file||busy)return;const corners=manualEditing&&manualBeforeCheck?manualDraft.map(p=>[...p]):null;if(corners&&!validBorder()){$('border-status').textContent='Use an uncrossed four-corner border with edges at least 10 pixels long.';return;}const ticket=start();try{const buffer=await file.arrayBuffer();if(ticket!==sequence)return;const bytes=new Uint8Array(buffer);let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const payload={image:btoa(binary)};if(corners)payload.crop_corners=corners;await request(payload,ticket);}catch(e){if(ticket===sequence){status('error','Unable to check this photo',e.message);busy=false;controls();}}};
$('clear').onclick=()=>{reset();releaseSelection();previousRetake=null;checks=0;$('session-count').textContent='Session · 0 checks';$('file').value='';$('file-name').textContent='No photo selected';controls();status('idle','Session cleared','The app released its image and result references. Source files and downloads remain on your device.');};
function download(data,name){const url=URL.createObjectURL(data);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('download').onclick=()=>{if(canExport())download(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),'capturegate-check.json');};
$('download-crop').onclick=()=>{if(!canExportAligned())return;const bytes=atob(imageData.document_preview.split(',')[1]);download(new Blob([Uint8Array.from(bytes,c=>c.charCodeAt(0))],{type:'image/jpeg'}),'capturegate-aligned-page.jpg');};
$('view-original').onclick=()=>setView(false);$('view-aligned').onclick=()=>setView(true);
function setTheme(theme){document.documentElement.dataset.theme=theme;$('theme-toggle').setAttribute('aria-label',theme==='dark'?'Switch to light theme':'Switch to dark theme');document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#0b1215':'#edf1ed';try{localStorage.setItem('capturegate-theme',theme);}catch{}}
let initialTheme='dark';try{if(localStorage.getItem('capturegate-theme')==='light')initialTheme='light';}catch{}setTheme(initialTheme);
$('theme-toggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
window.addEventListener('pagehide',()=>{if(selectedUrl)URL.revokeObjectURL(selectedUrl);});
if(window.location&&!['localhost','127.0.0.1','[::1]'].includes(window.location.hostname)){
 document.querySelector('.local').textContent='Server processing';
 document.querySelector('.privacy span').textContent='Uploaded to this demo server for processing. Use fictional documents only, never private records.';
}

// Shade removed geometry only: this is not text detection or a completeness claim.
function excludedPath(corners){
 if(!Array.isArray(corners)||corners.length!==4||corners.some(p=>!Array.isArray(p)||p.length!==2||p.some(v=>!Number.isFinite(v)||v<0||v>1)))return '';
 return 'M0 0H100V100H0Z M'+corners.map(p=>p.map(v=>v*100).join(' ')).join('L')+'Z';
}
function appliedCorners(){
 const g=imageData?.recovery?.geometry,size=imageData?.image_size;
 if(!recoveryCrop||!imageData?.recovery?.crop_applied)return fullBorder();
 if(g?.normalized_corners)return g.normalized_corners;
 if(g?.source_corners&&size)return g.source_corners.map(([x,y])=>[x/(size[0]-1),y/(size[1]-1)]);
 if(g?.source_box&&size){const [x,y,w,h]=g.source_box;return [[x,y],[x+w-1,y],[x+w-1,y+h-1],[x,y+h-1]].map(([a,b])=>[a/(size[0]-1),b/(size[1]-1)]);}
 return null;
}
const originalRenderRecovery=renderRecovery;
renderRecovery=function(){originalRenderRecovery();const path=excludedPath(appliedCorners());if(path)$('crop-loss-overlay').removeAttribute('hidden');else $('crop-loss-overlay').setAttribute('hidden','');$('crop-loss-path').setAttribute('d',path);$('crop-loss-note').textContent=path?'Orange shading on the original shows pixels excluded from this crop. Check signatures, numbers and page edges. It does not detect text or prove completeness.':'Crop exclusion geometry unavailable. Compare every needed line with the original.';};

function zipStored(files){
 const encoder=new TextEncoder(),parts=[],directory=[];let offset=0;
 function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
 function header(size){const a=new Uint8Array(size);return [a,new DataView(a.buffer)];}
 for(const [name,bytes] of files){const n=encoder.encode(name),checksum=crc(bytes),[h,v]=header(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(12,33,true);v.setUint32(14,checksum,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,n.length,true);parts.push(h,n,bytes);const [d,w]=header(46);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(14,33,true);w.setUint32(16,checksum,true);w.setUint32(20,bytes.length,true);w.setUint32(24,bytes.length,true);w.setUint16(28,n.length,true);w.setUint32(42,offset,true);directory.push(d,n);offset+=30+n.length+bytes.length;}
 const length=directory.reduce((s,b)=>s+b.length,0),[end,e]=header(22);e.setUint32(0,0x06054b50,true);e.setUint16(8,files.length,true);e.setUint16(10,files.length,true);e.setUint32(12,length,true);e.setUint32(16,offset,true);return new Blob([...parts,...directory,end],{type:'application/zip'});
}
async function reviewedBytes(variant,rotation){
 if(!rotation)return Uint8Array.from(atob(variant.image.split(',')[1]),c=>c.charCodeAt(0));
 const img=new Image();img.src=variant.image;await img.decode();const canvas=document.createElement('canvas');canvas.width=rotation%180?img.naturalHeight:img.naturalWidth;canvas.height=rotation%180?img.naturalWidth:img.naturalHeight;const c=canvas.getContext('2d');c.translate(canvas.width/2,canvas.height/2);c.rotate(rotation*Math.PI/180);c.drawImage(img,-img.naturalWidth/2,-img.naturalHeight/2);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.90));if(!blob)throw Error('Unable to encode image');return new Uint8Array(await blob.arrayBuffer());
}
async function handoffFiles(bytes,record){
 const digest=await crypto.subtle.digest('SHA-256',bytes),hash=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');
 const linked={...record,handoff:{schema:'capturegate-handoff-v1',image_file:'reviewed.jpg',output_sha256:hash,source_sha256:record.input_sha256||null,source_kind:record.source,identity_verified:false,whole_page_certified:false}};
 const summary=['CAPTUREGATE — HUMAN-REVIEWED HANDOFF','Image: reviewed.jpg','SHA-256: '+hash,'Original automatic decision: '+record.decision,'Original warnings: '+(record.reasons?.join(', ')||'None recorded'),'Review: '+JSON.stringify(record.user_review),'Source fingerprint: '+(record.input_sha256||'Unavailable; generated examples do not have an uploaded-file fingerprint.'),'Compare with the original. Acceptance is not a completeness or authenticity certificate.','Hashes link files; they do not prove who approved them.','The original photo is not included in this bundle.'].join('\n');
 const encoder=new TextEncoder();return [['reviewed.jpg',bytes],['review.json',encoder.encode(JSON.stringify(linked,null,2))],['READ-ME.txt',encoder.encode(summary)]];
}
// Place overlays inside the same image coordinate system, never over the rotated output.
document.querySelector('.border-overlay').prepend?.($('border-excluded'));
$('recovery-original-stage').append($('crop-loss-overlay'));
let packagingHandoff=false;
const originalRecoveryControls=recoveryControls;
recoveryControls=function(){originalRecoveryControls();$('download-bundle').disabled=packagingHandoff||!canExportRecovery();};
$('download-bundle').onclick=async()=>{
 if(!canExportRecovery()||packagingHandoff)return;
 const ticket=sequence,variant=recoveryVariant(),rotation=recoveryRotation,approval=report.user_review,snapshot=JSON.parse(JSON.stringify(report));packagingHandoff=true;$('download-bundle').disabled=true;
 const stillCurrent=()=>ticket===sequence&&variant===recoveryVariant()&&rotation===recoveryRotation&&report?.user_review===approval&&canExportRecovery();
 try{const bytes=await reviewedBytes(variant,rotation);const files=await handoffFiles(bytes,snapshot);if(stillCurrent())download(zipStored(files),'capturegate-reviewed-handoff.zip');}
 catch{if(stillCurrent())$('recovery-review-status').textContent='Unable to package this version. Your image is unchanged; retry on HTTPS or localhost.';}
 finally{packagingHandoff=false;$('download-bundle').disabled=!canExportRecovery();}
};
